# Generated by Django 6.1.1 on 2026-09-22 07:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_crop',
            field=models.JSONField(blank=True, null=True, verbose_name='recadrage de la photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_original',
            field=models.ImageField(blank=True, max_length=500, upload_to=accounts.models.avatar_original_upload_to),
        ),
    ]
