/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/admin/articles/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["admin_articles_list"];
		put?: never;
		post: operations["admin_articles_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/articles/{id}/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["admin_articles_retrieve"];
		put: operations["admin_articles_update"];
		post?: never;
		delete: operations["admin_articles_destroy"];
		options?: never;
		head?: never;
		patch: operations["admin_articles_partial_update"];
		trace?: never;
	};
	"/api/v1/admin/articles/{id}/cover/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["admin_articles_cover_create"];
		delete: operations["admin_articles_cover_destroy"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/articles/{id}/cover/crop/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description Re-crop the cover from its kept original. */
		post: operations["admin_articles_cover_crop_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/categories/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Authors may create categories (from the editor); editors and admins manage them. */
		get: operations["admin_categories_list"];
		put?: never;
		/** @description Authors may create categories (from the editor); editors and admins manage them. */
		post: operations["admin_categories_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/categories/{id}/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Authors may create categories (from the editor); editors and admins manage them. */
		get: operations["admin_categories_retrieve"];
		/** @description Authors may create categories (from the editor); editors and admins manage them. */
		put: operations["admin_categories_update"];
		post?: never;
		/** @description Authors may create categories (from the editor); editors and admins manage them. */
		delete: operations["admin_categories_destroy"];
		options?: never;
		head?: never;
		/** @description Authors may create categories (from the editor); editors and admins manage them. */
		patch: operations["admin_categories_partial_update"];
		trace?: never;
	};
	"/api/v1/admin/categories/reorder/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description Authors may create categories (from the editor); editors and admins manage them. */
		post: operations["admin_categories_reorder_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/preview/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description Render Markdown exactly as the public page will (same sanitiser). */
		post: operations["admin_preview_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/uploads/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["admin_uploads_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/users/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description User management, admin only. The last active admin cannot be demoted or disabled. */
		get: operations["admin_users_list"];
		put?: never;
		/** @description User management, admin only. The last active admin cannot be demoted or disabled. */
		post: operations["admin_users_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/users/{id}/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description User management, admin only. The last active admin cannot be demoted or disabled. */
		get: operations["admin_users_retrieve"];
		/** @description User management, admin only. The last active admin cannot be demoted or disabled. */
		put: operations["admin_users_update"];
		post?: never;
		/** @description User management, admin only. The last active admin cannot be demoted or disabled. */
		delete: operations["admin_users_destroy"];
		options?: never;
		head?: never;
		/** @description User management, admin only. The last active admin cannot be demoted or disabled. */
		patch: operations["admin_users_partial_update"];
		trace?: never;
	};
	"/api/v1/admin/users/{id}/avatar/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description User management, admin only. The last active admin cannot be demoted or disabled. */
		post: operations["admin_users_avatar_create"];
		/** @description User management, admin only. The last active admin cannot be demoted or disabled. */
		delete: operations["admin_users_avatar_destroy"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/admin/users/{id}/avatar/crop/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** @description User management, admin only. The last active admin cannot be demoted or disabled. */
		post: operations["admin_users_avatar_crop_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/articles/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Published articles only. ``?category=<slug>`` filters. */
		get: operations["articles_list"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/articles/{slug}/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Published articles only. ``?category=<slug>`` filters. */
		get: operations["articles_retrieve"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/csrf/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Sets the csrftoken cookie so the back-office can send X-CSRFToken. */
		get: operations["auth_csrf_retrieve"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/login/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["auth_login_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/logout/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["auth_logout_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/password-reset/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["auth_password_reset_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/password-reset/confirm/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["auth_password_reset_confirm_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/categories/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** @description Categories that have at least one published article. */
		get: operations["categories_list"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/me/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["me_retrieve"];
		put: operations["me_update"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: operations["me_partial_update"];
		trace?: never;
	};
	"/api/v1/me/avatar/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["me_avatar_create"];
		delete: operations["me_avatar_destroy"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/me/avatar/crop/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["me_avatar_crop_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/me/password/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["me_password_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/me/tokens/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["me_tokens_list"];
		put?: never;
		post: operations["me_tokens_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/me/tokens/{id}/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations["me_tokens_destroy"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/schema/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
		 *
		 *     - YAML: application/vnd.oai.openapi
		 *     - JSON: application/vnd.oai.openapi+json
		 */
		get: operations["schema_retrieve"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ApiToken: {
			/** Format: uuid */
			readonly id: string;
			name: string;
			readonly prefix: string;
			/** Format: date-time */
			readonly created_at: string;
			/** Format: date-time */
			readonly last_used_at: string | null;
		};
		/** @description Returned once, at creation: includes the raw token. */
		ApiTokenCreated: {
			/** Format: uuid */
			readonly id: string;
			name: string;
			readonly prefix: string;
			/** Format: date-time */
			readonly created_at: string;
			/** Format: date-time */
			readonly last_used_at: string | null;
			readonly token: string;
		};
		ApiTokenRequest: {
			name: string;
		};
		/** @description Back-office / MCP read-write representation. */
		Article: {
			/** Format: uuid */
			readonly id: string;
			/** Titre */
			title: string;
			slug: string;
			/** Résumé */
			summary: string;
			/** Contenu (Markdown) */
			body_markdown: string;
			readonly body_html: string;
			/** Format: uri-reference */
			readonly cover: string | null;
			/** Format: uri-reference */
			readonly cover_original: string | null;
			readonly cover_crop: components["schemas"]["Crop"] | null;
			/** Texte alternatif de la couverture */
			cover_alt: string;
			/**
			 * URL d'origine de la couverture
			 * Format: uri
			 * @description Adresse d'où l'image a été importée ; l'image elle-même est copiée dans le stockage.
			 */
			readonly cover_source_url: string;
			status: components["schemas"]["StatusEnum"];
			/**
			 * Date de publication
			 * Format: date-time
			 */
			published_at: string | null;
			readonly author: components["schemas"]["Author"];
			readonly categories: components["schemas"]["Category"][];
			/** Format: date-time */
			readonly created_at: string;
			/** Format: date-time */
			readonly updated_at: string;
		};
		ArticleImage: {
			/** Format: uuid */
			readonly id: string;
			/** Format: uri-reference */
			readonly url: string | null;
		};
		ArticleImageRequest: {
			/** Format: binary */
			file: string;
		};
		/** @description Back-office / MCP read-write representation. */
		ArticleRequest: {
			/** Titre */
			title: string;
			slug?: string;
			/** Résumé */
			summary?: string;
			/** Contenu (Markdown) */
			body_markdown?: string;
			/** Texte alternatif de la couverture */
			cover_alt?: string;
			status?: components["schemas"]["StatusEnum"];
			/**
			 * Date de publication
			 * Format: date-time
			 */
			published_at?: string | null;
			category_ids?: string[];
			/** @description Catégories par nom ; les catégories absentes sont créées. */
			category_names?: string[];
		};
		Author: {
			/** Format: uuid */
			readonly id: string;
			readonly name: string;
			/** Format: uri-reference */
			readonly avatar: string | null;
		};
		Category: {
			/** Format: uuid */
			readonly id: string;
			/** Nom */
			name: string;
			slug: string;
			/**
			 * Catégorie principale
			 * @description Affichée comme filtre principal sur la liste des articles.
			 */
			is_primary: boolean;
			order: number;
		};
		CategoryRequest: {
			/** Nom */
			name: string;
			slug?: string;
			/**
			 * Catégorie principale
			 * @description Affichée comme filtre principal sur la liste des articles.
			 */
			is_primary?: boolean;
			order?: number;
		};
		/** @description Category lists: adds how many articles use it (the view's annotation when present). */
		CategoryWithCount: {
			/** Format: uuid */
			readonly id: string;
			/** Nom */
			name: string;
			slug: string;
			/**
			 * Catégorie principale
			 * @description Affichée comme filtre principal sur la liste des articles.
			 */
			is_primary: boolean;
			order: number;
			readonly article_count: number;
		};
		/** @description Category lists: adds how many articles use it (the view's annotation when present). */
		CategoryWithCountRequest: {
			/** Nom */
			name: string;
			slug?: string;
			/**
			 * Catégorie principale
			 * @description Affichée comme filtre principal sur la liste des articles.
			 */
			is_primary?: boolean;
			order?: number;
		};
		CoverUploadRequest: {
			/** Format: binary */
			file?: string;
			/** Format: uri */
			url?: string;
			alt?: string;
		};
		/** @description Crop rectangle as fractions (0-1) of the original image. */
		Crop: {
			/** Format: double */
			x: number;
			/** Format: double */
			y: number;
			/** Format: double */
			width: number;
			/** Format: double */
			height: number;
		};
		/** @description Crop rectangle as fractions (0-1) of the original image. */
		CropRequest: {
			/** Format: double */
			x: number;
			/** Format: double */
			y: number;
			/** Format: double */
			width: number;
			/** Format: double */
			height: number;
		};
		ImageUploadRequest: {
			/** Format: binary */
			file?: string;
			/** Format: uri */
			url?: string;
		};
		LoginRequest: {
			/** Format: email */
			email: string;
			password: string;
		};
		PaginatedApiTokenList: {
			/** @example 123 */
			count: number;
			/**
			 * Format: uri
			 * @example http://api.example.org/accounts/?page=4
			 */
			next: string | null;
			/**
			 * Format: uri
			 * @example http://api.example.org/accounts/?page=2
			 */
			previous: string | null;
			results: components["schemas"]["ApiToken"][];
		};
		PaginatedArticleList: {
			/** @example 123 */
			count: number;
			/**
			 * Format: uri
			 * @example http://api.example.org/accounts/?page=4
			 */
			next: string | null;
			/**
			 * Format: uri
			 * @example http://api.example.org/accounts/?page=2
			 */
			previous: string | null;
			results: components["schemas"]["Article"][];
		};
		PaginatedPublicArticleList: {
			/** @example 123 */
			count: number;
			/**
			 * Format: uri
			 * @example http://api.example.org/accounts/?page=4
			 */
			next: string | null;
			/**
			 * Format: uri
			 * @example http://api.example.org/accounts/?page=2
			 */
			previous: string | null;
			results: components["schemas"]["PublicArticle"][];
		};
		PaginatedUserList: {
			/** @example 123 */
			count: number;
			/**
			 * Format: uri
			 * @example http://api.example.org/accounts/?page=4
			 */
			next: string | null;
			/**
			 * Format: uri
			 * @example http://api.example.org/accounts/?page=2
			 */
			previous: string | null;
			results: components["schemas"]["User"][];
		};
		PasswordChangeRequest: {
			current_password: string;
			new_password: string;
		};
		PasswordResetConfirmRequest: {
			uid: string;
			token: string;
			new_password: string;
		};
		PasswordResetRequestRequest: {
			/** Format: email */
			email: string;
		};
		/** @description Back-office / MCP read-write representation. */
		PatchedArticleRequest: {
			/** Titre */
			title?: string;
			slug?: string;
			/** Résumé */
			summary?: string;
			/** Contenu (Markdown) */
			body_markdown?: string;
			/** Texte alternatif de la couverture */
			cover_alt?: string;
			status?: components["schemas"]["StatusEnum"];
			/**
			 * Date de publication
			 * Format: date-time
			 */
			published_at?: string | null;
			category_ids?: string[];
			/** @description Catégories par nom ; les catégories absentes sont créées. */
			category_names?: string[];
		};
		/** @description Category lists: adds how many articles use it (the view's annotation when present). */
		PatchedCategoryWithCountRequest: {
			/** Nom */
			name?: string;
			slug?: string;
			/**
			 * Catégorie principale
			 * @description Affichée comme filtre principal sur la liste des articles.
			 */
			is_primary?: boolean;
			order?: number;
		};
		/** @description The current user's own profile; role and activation are not self-editable. */
		PatchedProfileRequest: {
			/**
			 * Adresse e-mail
			 * Format: email
			 */
			email?: string;
			/** Prénom */
			first_name?: string;
			/** Nom */
			last_name?: string;
		};
		PatchedUserRequest: {
			/**
			 * Adresse e-mail
			 * Format: email
			 */
			email?: string;
			/** Prénom */
			first_name?: string;
			/** Nom */
			last_name?: string;
			role?: components["schemas"]["RoleEnum"];
			/**
			 * Actif
			 * @description Précise si l’utilisateur doit être considéré comme actif. Décochez ceci plutôt que de supprimer le compte.
			 */
			is_active?: boolean;
		};
		PreviewRequest: {
			markdown: string;
		};
		PreviewResult: {
			html: string;
		};
		/** @description The current user's own profile; role and activation are not self-editable. */
		Profile: {
			/** Format: uuid */
			readonly id: string;
			/**
			 * Adresse e-mail
			 * Format: email
			 */
			email: string;
			/** Prénom */
			first_name: string;
			/** Nom */
			last_name: string;
			readonly role: components["schemas"]["RoleEnum"];
			/** Format: uri-reference */
			readonly avatar: string | null;
			/** Format: uri-reference */
			readonly avatar_original: string | null;
			readonly avatar_crop: components["schemas"]["Crop"] | null;
		};
		/** @description The current user's own profile; role and activation are not self-editable. */
		ProfileRequest: {
			/**
			 * Adresse e-mail
			 * Format: email
			 */
			email: string;
			/** Prénom */
			first_name?: string;
			/** Nom */
			last_name?: string;
		};
		PublicArticle: {
			/** Format: uuid */
			readonly id: string;
			slug: string;
			/** Titre */
			title: string;
			/** Résumé */
			summary: string;
			readonly categories: components["schemas"]["Category"][];
			/**
			 * Date de publication
			 * Format: date-time
			 */
			published_at: string | null;
			/** Format: uri-reference */
			readonly cover: string | null;
			/** Texte alternatif de la couverture */
			cover_alt: string;
			readonly author: components["schemas"]["Author"];
		};
		PublicArticleDetail: {
			/** Format: uuid */
			readonly id: string;
			slug: string;
			/** Titre */
			title: string;
			/** Résumé */
			summary: string;
			readonly categories: components["schemas"]["Category"][];
			/**
			 * Date de publication
			 * Format: date-time
			 */
			published_at: string | null;
			/** Format: uri-reference */
			readonly cover: string | null;
			/** Texte alternatif de la couverture */
			cover_alt: string;
			readonly author: components["schemas"]["Author"];
			readonly body_html: string;
			/** Format: date-time */
			readonly updated_at: string;
		};
		ReorderRequest: {
			ids: string[];
		};
		/**
		 * @description * `admin` - Administrateur
		 *     * `editor` - Éditeur
		 *     * `author` - Auteur
		 * @enum {string}
		 */
		RoleEnum: "admin" | "editor" | "author";
		/**
		 * @description * `draft` - Brouillon
		 *     * `published` - Publié
		 * @enum {string}
		 */
		StatusEnum: "draft" | "published";
		User: {
			/** Format: uuid */
			readonly id: string;
			/**
			 * Adresse e-mail
			 * Format: email
			 */
			email: string;
			/** Prénom */
			first_name: string;
			/** Nom */
			last_name: string;
			role: components["schemas"]["RoleEnum"];
			/** Format: uri-reference */
			readonly avatar: string | null;
			/** Format: uri-reference */
			readonly avatar_original: string | null;
			readonly avatar_crop: components["schemas"]["Crop"] | null;
			/**
			 * Actif
			 * @description Précise si l’utilisateur doit être considéré comme actif. Décochez ceci plutôt que de supprimer le compte.
			 */
			is_active: boolean;
			/**
			 * Date d’inscription
			 * Format: date-time
			 */
			readonly date_joined: string;
		};
		UserCreate: {
			/** Format: uuid */
			readonly id: string;
			/**
			 * Adresse e-mail
			 * Format: email
			 */
			email: string;
			/** Prénom */
			first_name: string;
			/** Nom */
			last_name: string;
			role: components["schemas"]["RoleEnum"];
			/** Format: uri-reference */
			readonly avatar: string | null;
			/** Format: uri-reference */
			readonly avatar_original: string | null;
			readonly avatar_crop: components["schemas"]["Crop"] | null;
			/**
			 * Actif
			 * @description Précise si l’utilisateur doit être considéré comme actif. Décochez ceci plutôt que de supprimer le compte.
			 */
			is_active: boolean;
			/**
			 * Date d’inscription
			 * Format: date-time
			 */
			readonly date_joined: string;
		};
		UserCreateRequest: {
			/**
			 * Adresse e-mail
			 * Format: email
			 */
			email: string;
			/** Prénom */
			first_name?: string;
			/** Nom */
			last_name?: string;
			role?: components["schemas"]["RoleEnum"];
			/**
			 * Actif
			 * @description Précise si l’utilisateur doit être considéré comme actif. Décochez ceci plutôt que de supprimer le compte.
			 */
			is_active?: boolean;
			password?: string;
		};
		UserRequest: {
			/**
			 * Adresse e-mail
			 * Format: email
			 */
			email: string;
			/** Prénom */
			first_name?: string;
			/** Nom */
			last_name?: string;
			role?: components["schemas"]["RoleEnum"];
			/**
			 * Actif
			 * @description Précise si l’utilisateur doit être considéré comme actif. Décochez ceci plutôt que de supprimer le compte.
			 */
			is_active?: boolean;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type ApiToken = components["schemas"]["ApiToken"];
export type ApiTokenCreated = components["schemas"]["ApiTokenCreated"];
export type ApiTokenRequest = components["schemas"]["ApiTokenRequest"];
export type Article = components["schemas"]["Article"];
export type ArticleImage = components["schemas"]["ArticleImage"];
export type ArticleImageRequest = components["schemas"]["ArticleImageRequest"];
export type ArticleRequest = components["schemas"]["ArticleRequest"];
export type Author = components["schemas"]["Author"];
export type Category = components["schemas"]["Category"];
export type CategoryRequest = components["schemas"]["CategoryRequest"];
export type CategoryWithCount = components["schemas"]["CategoryWithCount"];
export type CategoryWithCountRequest = components["schemas"]["CategoryWithCountRequest"];
export type CoverUploadRequest = components["schemas"]["CoverUploadRequest"];
export type Crop = components["schemas"]["Crop"];
export type CropRequest = components["schemas"]["CropRequest"];
export type ImageUploadRequest = components["schemas"]["ImageUploadRequest"];
export type LoginRequest = components["schemas"]["LoginRequest"];
export type PaginatedApiTokenList = components["schemas"]["PaginatedApiTokenList"];
export type PaginatedArticleList = components["schemas"]["PaginatedArticleList"];
export type PaginatedPublicArticleList = components["schemas"]["PaginatedPublicArticleList"];
export type PaginatedUserList = components["schemas"]["PaginatedUserList"];
export type PasswordChangeRequest = components["schemas"]["PasswordChangeRequest"];
export type PasswordResetConfirmRequest = components["schemas"]["PasswordResetConfirmRequest"];
export type PasswordResetRequestRequest = components["schemas"]["PasswordResetRequestRequest"];
export type PatchedArticleRequest = components["schemas"]["PatchedArticleRequest"];
export type PatchedCategoryWithCountRequest =
	components["schemas"]["PatchedCategoryWithCountRequest"];
export type PatchedProfileRequest = components["schemas"]["PatchedProfileRequest"];
export type PatchedUserRequest = components["schemas"]["PatchedUserRequest"];
export type PreviewRequest = components["schemas"]["PreviewRequest"];
export type PreviewResult = components["schemas"]["PreviewResult"];
export type Profile = components["schemas"]["Profile"];
export type ProfileRequest = components["schemas"]["ProfileRequest"];
export type PublicArticle = components["schemas"]["PublicArticle"];
export type PublicArticleDetail = components["schemas"]["PublicArticleDetail"];
export type ReorderRequest = components["schemas"]["ReorderRequest"];
export type RoleEnum = components["schemas"]["RoleEnum"];
export type StatusEnum = components["schemas"]["StatusEnum"];
export type User = components["schemas"]["User"];
export type UserCreate = components["schemas"]["UserCreate"];
export type UserCreateRequest = components["schemas"]["UserCreateRequest"];
export type UserRequest = components["schemas"]["UserRequest"];
export type $defs = Record<string, never>;
export interface operations {
	admin_articles_list: {
		parameters: {
			query?: {
				author?: string;
				category?: string;
				/** @description Quel champ utiliser pour classer les résultats. */
				ordering?: string;
				/** @description Un numéro de page de l'ensemble des résultats. */
				page?: number;
				/** @description Nombre de résultats à retourner par page. */
				page_size?: number;
				/** @description Un terme de recherche. */
				search?: string;
				/**
				 * @description * `draft` - Brouillon
				 *     * `published` - Publié
				 */
				status?: "draft" | "published";
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PaginatedArticleList"];
				};
			};
		};
	};
	admin_articles_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ArticleRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["ArticleRequest"];
				"multipart/form-data": components["schemas"]["ArticleRequest"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Article"];
				};
			};
		};
	};
	admin_articles_retrieve: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) article. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Article"];
				};
			};
		};
	};
	admin_articles_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) article. */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ArticleRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["ArticleRequest"];
				"multipart/form-data": components["schemas"]["ArticleRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Article"];
				};
			};
		};
	};
	admin_articles_destroy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) article. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	admin_articles_partial_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) article. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": components["schemas"]["PatchedArticleRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["PatchedArticleRequest"];
				"multipart/form-data": components["schemas"]["PatchedArticleRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Article"];
				};
			};
		};
	};
	admin_articles_cover_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) article. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"multipart/form-data": components["schemas"]["CoverUploadRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["CoverUploadRequest"];
				"application/json": components["schemas"]["CoverUploadRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Article"];
				};
			};
		};
	};
	admin_articles_cover_destroy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) article. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	admin_articles_cover_crop_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) article. */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CropRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["CropRequest"];
				"multipart/form-data": components["schemas"]["CropRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Article"];
				};
			};
		};
	};
	admin_categories_list: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CategoryWithCount"][];
				};
			};
		};
	};
	admin_categories_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CategoryWithCountRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["CategoryWithCountRequest"];
				"multipart/form-data": components["schemas"]["CategoryWithCountRequest"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CategoryWithCount"];
				};
			};
		};
	};
	admin_categories_retrieve: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) catégorie. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CategoryWithCount"];
				};
			};
		};
	};
	admin_categories_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) catégorie. */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CategoryWithCountRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["CategoryWithCountRequest"];
				"multipart/form-data": components["schemas"]["CategoryWithCountRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CategoryWithCount"];
				};
			};
		};
	};
	admin_categories_destroy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) catégorie. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	admin_categories_partial_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) catégorie. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": components["schemas"]["PatchedCategoryWithCountRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["PatchedCategoryWithCountRequest"];
				"multipart/form-data": components["schemas"]["PatchedCategoryWithCountRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CategoryWithCount"];
				};
			};
		};
	};
	admin_categories_reorder_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ReorderRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["ReorderRequest"];
				"multipart/form-data": components["schemas"]["ReorderRequest"];
			};
		};
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	admin_preview_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PreviewRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["PreviewRequest"];
				"multipart/form-data": components["schemas"]["PreviewRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PreviewResult"];
				};
			};
		};
	};
	admin_uploads_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"multipart/form-data": components["schemas"]["ArticleImageRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["ArticleImageRequest"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ArticleImage"];
				};
			};
		};
	};
	admin_users_list: {
		parameters: {
			query?: {
				is_active?: boolean;
				/** @description Un numéro de page de l'ensemble des résultats. */
				page?: number;
				/** @description Nombre de résultats à retourner par page. */
				page_size?: number;
				/**
				 * @description * `admin` - Administrateur
				 *     * `editor` - Éditeur
				 *     * `author` - Auteur
				 */
				role?: "admin" | "author" | "editor";
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PaginatedUserList"];
				};
			};
		};
	};
	admin_users_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserCreateRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["UserCreateRequest"];
				"multipart/form-data": components["schemas"]["UserCreateRequest"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserCreate"];
				};
			};
		};
	};
	admin_users_retrieve: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) user. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["User"];
				};
			};
		};
	};
	admin_users_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) user. */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
				"multipart/form-data": components["schemas"]["UserRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["User"];
				};
			};
		};
	};
	admin_users_destroy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) user. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	admin_users_partial_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) user. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": components["schemas"]["PatchedUserRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
				"multipart/form-data": components["schemas"]["PatchedUserRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["User"];
				};
			};
		};
	};
	admin_users_avatar_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) user. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"multipart/form-data": components["schemas"]["ImageUploadRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["ImageUploadRequest"];
				"application/json": components["schemas"]["ImageUploadRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["User"];
				};
			};
		};
	};
	admin_users_avatar_destroy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) user. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	admin_users_avatar_crop_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) user. */
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CropRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["CropRequest"];
				"multipart/form-data": components["schemas"]["CropRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["User"];
				};
			};
		};
	};
	articles_list: {
		parameters: {
			query?: {
				category?: string;
				/** @description Un numéro de page de l'ensemble des résultats. */
				page?: number;
				/** @description Nombre de résultats à retourner par page. */
				page_size?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PaginatedPublicArticleList"];
				};
			};
		};
	};
	articles_retrieve: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PublicArticleDetail"];
				};
			};
		};
	};
	auth_csrf_retrieve: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	auth_login_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
				"multipart/form-data": components["schemas"]["LoginRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Profile"];
				};
			};
		};
	};
	auth_logout_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	auth_password_reset_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PasswordResetRequestRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequestRequest"];
				"multipart/form-data": components["schemas"]["PasswordResetRequestRequest"];
			};
		};
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	auth_password_reset_confirm_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PasswordResetConfirmRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
				"multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
			};
		};
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	categories_list: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CategoryWithCount"][];
				};
			};
		};
	};
	me_retrieve: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Profile"];
				};
			};
		};
	};
	me_update: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ProfileRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["ProfileRequest"];
				"multipart/form-data": components["schemas"]["ProfileRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Profile"];
				};
			};
		};
	};
	me_partial_update: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": components["schemas"]["PatchedProfileRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["PatchedProfileRequest"];
				"multipart/form-data": components["schemas"]["PatchedProfileRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Profile"];
				};
			};
		};
	};
	me_avatar_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				"multipart/form-data": components["schemas"]["ImageUploadRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["ImageUploadRequest"];
				"application/json": components["schemas"]["ImageUploadRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["User"];
				};
			};
		};
	};
	me_avatar_destroy: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	me_avatar_crop_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CropRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["CropRequest"];
				"multipart/form-data": components["schemas"]["CropRequest"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["User"];
				};
			};
		};
	};
	me_password_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PasswordChangeRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
				"multipart/form-data": components["schemas"]["PasswordChangeRequest"];
			};
		};
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	me_tokens_list: {
		parameters: {
			query?: {
				/** @description Un numéro de page de l'ensemble des résultats. */
				page?: number;
				/** @description Nombre de résultats à retourner par page. */
				page_size?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PaginatedApiTokenList"];
				};
			};
		};
	};
	me_tokens_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ApiTokenRequest"];
				"application/x-www-form-urlencoded": components["schemas"]["ApiTokenRequest"];
				"multipart/form-data": components["schemas"]["ApiTokenRequest"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiTokenCreated"];
				};
			};
		};
	};
	me_tokens_destroy: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Un(une) Chaîne UUID identifiant ce(cette) api token. */
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No response body */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	schema_retrieve: {
		parameters: {
			query?: {
				format?: "json" | "yaml";
				lang?:
					| "af"
					| "ar"
					| "ar-dz"
					| "ast"
					| "az"
					| "be"
					| "bg"
					| "bn"
					| "br"
					| "bs"
					| "ca"
					| "ckb"
					| "cs"
					| "cy"
					| "da"
					| "de"
					| "dsb"
					| "el"
					| "en"
					| "en-au"
					| "en-gb"
					| "eo"
					| "es"
					| "es-ar"
					| "es-co"
					| "es-mx"
					| "es-ni"
					| "es-ve"
					| "et"
					| "eu"
					| "fa"
					| "fi"
					| "fr"
					| "fy"
					| "ga"
					| "gd"
					| "gl"
					| "he"
					| "hi"
					| "hr"
					| "hsb"
					| "ht"
					| "hu"
					| "hy"
					| "ia"
					| "id"
					| "ig"
					| "io"
					| "is"
					| "it"
					| "ja"
					| "ka"
					| "kab"
					| "kk"
					| "km"
					| "kn"
					| "ko"
					| "ky"
					| "lb"
					| "lt"
					| "lv"
					| "mk"
					| "ml"
					| "mn"
					| "mr"
					| "ms"
					| "my"
					| "nb"
					| "ne"
					| "nl"
					| "nn"
					| "os"
					| "pa"
					| "pl"
					| "pt"
					| "pt-br"
					| "ro"
					| "ru"
					| "sk"
					| "sl"
					| "sq"
					| "sr"
					| "sr-latn"
					| "sv"
					| "sw"
					| "ta"
					| "te"
					| "tg"
					| "th"
					| "tk"
					| "tr"
					| "tt"
					| "udm"
					| "ug"
					| "uk"
					| "ur"
					| "uz"
					| "vi"
					| "zh-hans"
					| "zh-hant";
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/vnd.oai.openapi": {
						[key: string]: unknown;
					};
					"application/yaml": {
						[key: string]: unknown;
					};
					"application/vnd.oai.openapi+json": {
						[key: string]: unknown;
					};
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
		};
	};
}
