# Generated by Django 6.1.1 on 2026-09-21 13:21

import articles.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Affichée comme filtre principal sur la liste des articles.', verbose_name='catégorie principale')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'catégorie',
                'ordering': ['-is_primary', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(max_length=500, upload_to=articles.models.inline_upload_to)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('body_markdown', models.TextField(blank=True, verbose_name='contenu (Markdown)')),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('cover', models.ImageField(blank=True, max_length=500, upload_to=articles.models.cover_upload_to)),
                ('cover_alt', models.CharField(blank=True, max_length=200, verbose_name='texte alternatif de la couverture')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='articles.category')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='articles_ar_status_de59cf_idx')],
            },
        ),
    ]
