# Generated by Django 6.1.1 on 2026-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_source_url',
            field=models.URLField(blank=True, help_text="Adresse d'où l'image a été importée ; l'image elle-même est copiée dans le stockage.", max_length=2000, verbose_name="URL d'origine de la couverture"),
        ),
    ]
