# Generated by Django 6.1.1 on 2026-09-22 07:21

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_cover_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_crop',
            field=models.JSONField(blank=True, null=True, verbose_name='recadrage de la couverture'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_original',
            field=models.ImageField(blank=True, max_length=500, upload_to=articles.models.cover_original_upload_to),
        ),
    ]
