# Generated by Django 6.1.1 on 2026-09-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_image_originals_and_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name="adresse d'origine"),
        ),
    ]
